### ISSUE TITLE
localhost:5000/devices post not working

### ISSUE THREAD

**Issue by nirojshrestha019** [jakewright/tutorials#16]
The body of the post is as follows:
```
{
    "identifier": "abcs",
    "name": "Floor Lamp",
    "device_type": "switch",
    "controller_gateway": "123456789"
}
```
And here is the issue am getting, not sure what the issue is:
HELP NEEDED.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/src/app/device_registry/__init__.py", line 62, in post
    args = parser.parse_args()
  File "/usr/local/lib/python3.9/site-packages/flask_restful/reqparse.py", line 305, in parse_args
    value, found = arg.parse(req, self.bundle_errors)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/reqparse.py", line 163, in parse
    source = self.source(request)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/reqparse.py", line 108, in source
    values.update(value)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/datastructures.py", line 554, in update
    for key, value in iter_multi_items(mapping):
TypeError: cannot unpack non-iterable ellipsis object

**Comment by yeatfaicheong** [comment]
Hi there,
It has something to do with the package version in the requirements.txt

Changing the requirements.txt works for me.

Flask==2.0.1
flask-restful==0.3.9
markdown==2.6.11

Reference from Stackoverflow here:
https://stackoverflow.com/questions/68120834/non-iterable-ellipsis-in-flask-restful-parser-parse-args
